/* eslint-disable sonarjs/no-duplicate-string -- mock data only */
export const res = {
  data: {
    result: {
      data: {
        elementIds: [1284],
        elementPeriods: {
          '1284': [
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230106,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 1308,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 1015,
              hasPeriodText: false,
              id: 1004172,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 23999,
              lessonNumber: 15800,
              lessonText: '',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 930,
              studentCount: 0,
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230106,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 1308,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 1100,
              hasPeriodText: false,
              id: 1004177,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 23999,
              lessonNumber: 15800,
              lessonText: '',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 1015,
              studentCount: 0,
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230106,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 1308,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 1400,
              hasPeriodText: false,
              id: 1252080,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 23999,
              lessonNumber: 15800,
              lessonText: '',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 1315,
              studentCount: 0,
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230106,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 1308,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 1445,
              hasPeriodText: false,
              id: 1252085,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 23999,
              lessonNumber: 15800,
              lessonText: '',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 1400,
              studentCount: 0,
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230105,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 1313,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 1015,
              hasPeriodText: false,
              id: 1283453,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 27835,
              lessonNumber: 94600,
              lessonText: 'Gr. A',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 930,
              studentCount: 0,
              studentGroup: 'KBM_L02_KBM22a_4',
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230105,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 1313,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 1100,
              hasPeriodText: false,
              id: 1283458,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 27835,
              lessonNumber: 94600,
              lessonText: 'Gr. A',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 1015,
              studentCount: 0,
              studentGroup: 'KBM_L02_KBM22a_4',
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230105,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 1313,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 1015,
              hasPeriodText: false,
              id: 1283513,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 27840,
              lessonNumber: 94700,
              lessonText: 'Gr. B',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 930,
              studentCount: 0,
              studentGroup: 'KBM_L02_KBM22a_3',
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230105,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 1313,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 1100,
              hasPeriodText: false,
              id: 1283518,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 27840,
              lessonNumber: 94700,
              lessonText: 'Gr. B',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 1015,
              studentCount: 0,
              studentGroup: 'KBM_L02_KBM22a_3',
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230105,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 1323,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 830,
              hasPeriodText: false,
              id: 1006192,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 24039,
              lessonNumber: 16100,
              lessonText: 'Gr. A, Gr. B',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 745,
              studentCount: 0,
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230105,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 1323,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 915,
              hasPeriodText: false,
              id: 1006197,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 24039,
              lessonNumber: 16100,
              lessonText: 'Gr. A, Gr. B',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 830,
              studentCount: 0,
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230106,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 1323,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 830,
              hasPeriodText: false,
              id: 1006202,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 24039,
              lessonNumber: 16100,
              lessonText: 'Gr. A, Gr. B',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 745,
              studentCount: 0,
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230106,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 1323,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 915,
              hasPeriodText: false,
              id: 1006207,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 24039,
              lessonNumber: 16100,
              lessonText: 'Gr. A, Gr. B',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 830,
              studentCount: 0,
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230106,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 1323,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 1200,
              hasPeriodText: false,
              id: 1006212,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 24039,
              lessonNumber: 16100,
              lessonText: 'Gr. A, Gr. B',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 1115,
              studentCount: 0,
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230106,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 1323,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 1245,
              hasPeriodText: false,
              id: 1006217,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 24039,
              lessonNumber: 16100,
              lessonText: 'Gr. A, Gr. B',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 1200,
              studentCount: 0,
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230105,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 2125,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 1200,
              hasPeriodText: false,
              id: 1103042,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 25610,
              lessonNumber: 16700,
              lessonText: 'ECDL',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 1115,
              studentCount: 0,
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230105,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 2125,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 1245,
              hasPeriodText: false,
              id: 1103047,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 25610,
              lessonNumber: 16700,
              lessonText: 'ECDL',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 1200,
              studentCount: 0,
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230105,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 2125,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 1400,
              hasPeriodText: false,
              id: 1103052,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 25610,
              lessonNumber: 16700,
              lessonText: 'ECDL',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 1315,
              studentCount: 0,
              substText: '',
            },
            {
              cellState: 'STANDARD',
              code: 0,
              date: 20230105,
              elements: [
                {
                  id: 1284,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 1,
                },
                {
                  id: 2125,
                  missing: false,
                  orgId: 0,
                  state: 'REGULAR',
                  type: 3,
                },
              ],
              endTime: 1445,
              hasPeriodText: false,
              id: 1103057,
              is: {
                event: false,
                standard: true,
              },
              lessonCode: 'LESSON',
              lessonId: 25610,
              lessonNumber: 16700,
              lessonText: 'ECDL',
              periodAttachments: [],
              periodInfo: '',
              periodText: '',
              priority: 5,
              roomCapacity: 0,
              startTime: 1400,
              studentCount: 0,
              substText: '',
            },
          ],
        },
        elements: [
          {
            alternatename: '',
            canViewTimetable: true,
            displayname: 'KBM22a',
            id: 1284,
            longName: 'Kaufmann/-frau für Büromanagement GS - Block',
            name: 'KBM22a',
            roomCapacity: 0,
            type: 1,
          },
          {
            alternatename: '124',
            canViewTimetable: true,
            displayname: 'KBM_L01',
            id: 1308,
            longName: 'Die eigene Rolle im Bet .. n Betrieb präsentieren',
            name: 'KBM_L01',
            roomCapacity: 0,
            type: 3,
          },
          {
            alternatename: '124',
            canViewTimetable: true,
            displayname: 'WPF_ECDL',
            id: 2125,
            longName: 'Wahlpflichtfach ECDL KBM Block Europakaufmann',
            name: 'WPF_ECDL',
            roomCapacity: 0,
            type: 3,
          },
          {
            alternatename: '124',
            canViewTimetable: true,
            displayname: 'KBM_L02',
            id: 1313,
            longName: 'Büroprozesse gestalten  .. svorgänge organisieren',
            name: 'KBM_L02',
            roomCapacity: 0,
            type: 3,
          },
          {
            alternatename: '124',
            canViewTimetable: true,
            displayname: 'KBM_L04',
            id: 1323,
            longName: 'Sachgüter und Dienstlei .. und Verträge schließen',
            name: 'KBM_L04',
            roomCapacity: 0,
            type: 3,
          },
        ],
        noDetails: true,
      },
      lastImportTimestamp: 1671198496350,
    },
  },
};
